In [59]:
myfile = open("Numbers.txt", "w")
import random
for i in range(0,4):
    number = random.randint(0,100)
    myfile.write(str(number))
    myfile.write("\n")

myfile.close()

In [60]:
myfile = open("Numbers.txt", "r")
data = myfile.read().replace("\n", ", ")
myfile.close()
print(data)

79, 17, 33, 71, 


In [84]:
def mark_grade():
    percent = int(input("What percentage mark did you get for your last exam?"))
    return percent

In [88]:
score = mark_grade()
if score >= 90:
    print("Congratulations you have achieved an A*")
elif score >= 80 and score <= 89:
    print("Well done you have achieved an A!")
elif score >= 70 and score <=79:
    print("Good job you scored a B.")
elif score >= 60 and score <=69:
    print("You achieved a C.")
else:
    print("Sorry, you failed.")

Well done you have achieved an A!


In [200]:
import numpy as np
first = np.arange(10)
print(first)

second = np.ones((3,3))
print(second==1)

third = np.arange(1,11)
odd = third % 2 == 1
third[odd] = -1
print(third)

fourth = first.reshape(2,5)
print(fourth)

a = np.arange(3,28,3).reshape(3,3)
b = np.arange(30,55,3).reshape(3,3)
c = np.dot(a,b)
print(c)
d = np.sum(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[-1  2 -1  4 -1  6 -1  8 -1 10]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 756  810  864]
 [1809 1944 2079]
 [2862 3078 3294]]
17496
